import { s_sub } from "./scripts/streaming-subscriber.js";
import { s_web } from "./scripts/streaming-websocket.js";

/* To run smoke test: RUN_LIVE_TESTS=1 npm run test:live:smoke */
export * from "./account/index.js";
export * from "./derivatives/index.js";
export * from "./market-data/index.js";
export * from "./oauth/schwabAuth.js";
export { SchwabStreamer } from "./streaming/websocket/index.js";
export type {
  AcctActivityFieldId,
  AcctActivityFieldName,
  AcctActivitySubscriptionInput,
  BookFieldId,
  BookFieldName,
  BookMarketMakerFieldId,
  BookMarketMakerFieldName,
  BookPriceLevelFieldId,
  BookPriceLevelFieldName,
  ChartEquityFieldId,
  ChartEquityFieldName,
  ChartEquitySubscriptionInput,
  ChartEquityViewInput,
  ChartFuturesFieldId,
  ChartFuturesFieldName,
  ChartFuturesSubscriptionInput,
  ChartFuturesViewInput,
  L2NasdaqBookSubscriptionInput,
  L2NasdaqBookViewInput,
  L2NyseBookSubscriptionInput,
  L2NyseBookViewInput,
  L2OptionsBookSubscriptionInput,
  L2OptionsBookViewInput,
  ScreenerEquitySubscriptionInput,
  ScreenerEquityViewInput,
  ScreenerFieldId,
  ScreenerFieldName,
  ScreenerOptionSubscriptionInput,
  ScreenerOptionViewInput,
  LevelOneEquitiesFieldId,
  LevelOneEquitiesFieldName,
  LevelOneEquitiesSubscriptionInput,
  LevelOneEquitiesViewInput,
  LevelOneForexFieldId,
  LevelOneForexFieldName,
  LevelOneForexSubscriptionInput,
  LevelOneForexViewInput,
  LevelOneFuturesFieldId,
  LevelOneFuturesFieldName,
  LevelOneFuturesSubscriptionInput,
  LevelOneFuturesOptionsFieldId,
  LevelOneFuturesOptionsFieldName,
  LevelOneFuturesOptionsSubscriptionInput,
  LevelOneFuturesOptionsViewInput,
  LevelOneFuturesViewInput,
  LevelOneOptionsFieldId,
  LevelOneOptionsFieldName,
  LevelOneOptionsSubscriptionInput,
  LevelOneOptionsViewInput,
  StreamCommand,
  StreamService,
  SubscriptionInput,
  SubscriptionState,
  UnsubscribeInput,
  ViewInput,
} from "./streaming/websocket/index.js";
export {
  ACCT_ACTIVITY_FIELDS,
  ACCT_ACTIVITY_FIELD_IDS_BY_NAME,
  BOOK_FIELDS,
  BOOK_FIELD_IDS_BY_NAME,
  BOOK_MARKET_MAKER_FIELDS,
  BOOK_MARKET_MAKER_FIELD_IDS_BY_NAME,
  BOOK_PRICE_LEVEL_FIELDS,
  BOOK_PRICE_LEVEL_FIELD_IDS_BY_NAME,
  CHART_EQUITY_FIELDS,
  CHART_EQUITY_FIELD_IDS_BY_NAME,
  CHART_FUTURES_FIELDS,
  CHART_FUTURES_FIELD_IDS_BY_NAME,
  LEVELONE_EQUITIES_FIELDS,
  LEVELONE_EQUITIES_FIELD_IDS_BY_NAME,
  LEVELONE_OPTIONS_FIELDS,
  LEVELONE_OPTIONS_FIELD_IDS_BY_NAME,
  LEVELONE_FUTURES_FIELDS,
  LEVELONE_FUTURES_FIELD_IDS_BY_NAME,
  LEVELONE_FUTURES_OPTIONS_FIELDS,
  LEVELONE_FUTURES_OPTIONS_FIELD_IDS_BY_NAME,
  LEVELONE_FOREX_FIELDS,
  LEVELONE_FOREX_FIELD_IDS_BY_NAME,
  SCREENER_FIELDS,
  SCREENER_FIELD_IDS_BY_NAME,
  resolveFieldIds,
  resolveFieldNames,
  resolveAcctActivityFieldIds,
  resolveAcctActivityFieldNames,
  resolveBookFieldIds,
  resolveBookFieldNames,
  resolveBookMarketMakerFieldIds,
  resolveBookPriceLevelFieldIds,
  resolveChartEquityFieldIds,
  resolveChartEquityFieldNames,
  resolveChartFuturesFieldIds,
  resolveChartFuturesFieldNames,
  resolveLevelOneEquitiesFieldIds,
  resolveLevelOneEquitiesFieldNames,
  resolveLevelOneForexFieldIds,
  resolveLevelOneForexFieldNames,
  resolveLevelOneFuturesFieldIds,
  resolveLevelOneFuturesFieldNames,
  resolveLevelOneFuturesOptionsFieldIds,
  resolveLevelOneFuturesOptionsFieldNames,
  resolveScreenerFieldIds,
  resolveScreenerFieldNames,
  resolveLevelOneOptionsFieldIds,
  resolveLevelOneOptionsFieldNames,
} from "./streaming/websocket/index.js";
export type {
  AtmOptionRtn,
  ChartBase,
  ChartRequest,
  DailyFrequency,
  DailyFrequencyType,
  DayFrequencyType,
  DayPeriod,
  ExpDateMap,
  ExpirationKey,
  FrequencyFor,
  GetAtmOptionReq,
  GetOptionChainRtn,
  GetQuoteReq,
  GreekFilterReq,
  GreekFilterRtn,
  ISODate,
  MinuteFrequency,
  MinuteFrequencyType,
  MonthFrequencyType,
  MonthlyFrequency,
  MonthlyFrequencyType,
  MonthPeriod,
  OptionChainReq,
  OptionExpirationReq,
  OptionExpirationRtn,
  OptionSide,
  OptionSideMaps,
  PeriodType,
  PriceHistoryRtnElement,
  QuoteData,
  QuoteRtn,
  ScreenersResponseItem,
  StrikeKey,
  StrikeMap,
  SymbolString,
  WeeklyFrequency,
  WeeklyFrequencyType,
  YearFrequencyType,
  YearPeriod,
  YtdFrequencyType,
  YtdPeriod,
} from "./types.js";

(async function () {

  s_sub();
  await s_web();
})();
